const express = require("express");
const multer = require("multer");
const axios = require("axios");
const cors = require("cors");

const app = express();
app.use(cors());
app.use(express.json());

const storage = multer.memoryStorage();
const upload = multer({ storage: storage });

const GEMINI_MODEL = "gemini-2.5-flash-preview-09-2025";
const GEMINI_API_URL =
  `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

const GEMINI_API_KEY = "AIzaSyASM5Xz5xBtz-4qSaCksuqwo18unW4tYTc";

app.post("/process-image", upload.single("file"), async (req, res) => {
  try {
    if (!GEMINI_API_KEY) {
      console.error("❌ GEMINI_API_KEY environment variable not set.");
      return res.status(500).json({
        error: "Server configuration error: API key not set.",
      });
    }

    if (!req.file) {
      return res.status(400).json({ error: "No file uploaded" });
    }

    const prompt = req.body.prompt || "Describe this image briefly.";

    // Convert image buffer to Base64
    const imageBase64 = req.file.buffer.toString("base64");

    // Corrected payload structure for Gemini API
    const payload = {
      contents: [
        {
          // Added role: "user"
          role: "user",
          parts: [
            { text: prompt },
            {
              // Corrected: 'inlineData' (not 'inline_data')
              inlineData: {
                // Corrected: 'mimeType' (not 'mime_type')
                mimeType: req.file.mimetype,
                data: imageBase64,
              },
            },
          ],
        },
      ],
    };

    const response = await axios.post(
      `${GEMINI_API_URL}?key=${GEMINI_API_KEY}`,
      payload,
      {
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    // Extract the text response
    const textResponse =
      response.data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!textResponse) {
      console.warn("⚠️ Gemini response missing expected text part.", response.data);
      return res.json({
        success: true,
        llm_output: "No text response generated by the model.",
      });
    }

    res.json({
      success: true,
      llm_output: textResponse,
    });

  } catch (error) {
    // Log more detailed error information
    console.error("❌ Gemini Error:", error.message);
    if (error.response) {
      console.error("Data:", error.response.data);
      console.error("Status:", error.response.status);
      console.error("Headers:", error.response.headers);
    } else if (error.request) {
      console.error("Request:", error.request);
    }

    res.status(500).json({
      error: "Failed to process image with Gemini",
      details: error.response?.data?.error?.message || error.message,
    });
  }
});


app.post("/ask-question", async (req, res) => {
  try {
    if (!GEMINI_API_KEY) {
      console.error("❌ GEMINI_API_KEY environment variable not set.");
      return res.status(500).json({
        error: "Server configuration error: API key not set.",
      });
    }

    const { prompt } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: "No prompt provided" });
    }

    
    const systemInstruction = {
      parts: [{
        text: "You are a fun assistant. Your replies should be short and a little silly, while still being helpful and answering the question."
      }]
    };

    const payload = {
      contents: [
        {
          role: "user",
          parts: [{ text: prompt }],
        },
      ],
    
      systemInstruction: systemInstruction,
    };

    const response = await axios.post(
      `${GEMINI_API_URL}?key=${GEMINI_API_KEY}`,
      payload,
      {
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    const textResponse =
      response.data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!textResponse) {
      console.warn("⚠️ Gemini response missing expected text part.", response.data);
      return res.json({
        success: true,
        llm_output: "The model was too goofy and forgot to reply!",
      });
    }

    res.json({
      success: true,
      llm_output: textResponse,
    });

  } catch (error) {
    
    console.error("❌ Gemini Error (/ask-question):", error.message);
    if (error.response) {
      console.error("Data:", error.response.data);
      console.error("Status:", error.response.status);
    } else if (error.request) {
      console.error("Request:", error.request);
    }

    res.status(500).json({
      error: "Failed to process text prompt with Gemini",
      details: error.response?.data?.error?.message || error.message,
    });
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 Server running on port ${PORT}`);
  console.log(`POST to http://localhost:${PORT}/process-image`);
  console.log(`POST to http://localhost:${PORT}/ask-question`); 
  if (!GEMINI_API_KEY) {
    console.warn("⚠️ WARNING: GEMINI_API_KEY environment variable is not set!");
    console.warn("The /process-image endpoint will not work until it is set.");
  }
});