// const express = require("express");
// const multer = require("multer");
// const axios = require("axios");
// const cors = require("cors");

// const app = express();
// app.use(cors());
// app.use(express.json());

// const storage = multer.memoryStorage();
// const upload = multer({ storage: storage });

// const GEMINI_MODEL = "gemini-2.5-flash-preview-09-2025";
// const GEMINI_API_URL =
//   `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

// const GEMINI_API_KEY = "AIzaSyASM5Xz5xBtz-4qSaCksuqwo18unW4tYTc";

// app.post("/process-image", upload.single("file"), async (req, res) => {
//   try {
//     if (!GEMINI_API_KEY) {
//       console.error("❌ GEMINI_API_KEY environment variable not set.");
//       return res.status(500).json({
//         error: "Server configuration error: API key not set.",
//       });
//     }

//     if (!req.file) {
//       return res.status(400).json({ error: "No file uploaded" });
//     }

//     const prompt = req.body.prompt || "Describe this image briefly.";

//     // Convert image buffer to Base64
//     const imageBase64 = req.file.buffer.toString("base64");

//     // Corrected payload structure for Gemini API
//     const payload = {
//       contents: [
//         {
//           // Added role: "user"
//           role: "user",
//           parts: [
//             { text: prompt },
//             {
//               // Corrected: 'inlineData' (not 'inline_data')
//               inlineData: {
//                 // Corrected: 'mimeType' (not 'mime_type')
//                 mimeType: req.file.mimetype,
//                 data: imageBase64,
//               },
//             },
//           ],
//         },
//       ],
//     };

//     const response = await axios.post(
//       `${GEMINI_API_URL}?key=${GEMINI_API_KEY}`,
//       payload,
//       {
//         headers: {
//           "Content-Type": "application/json",
//         },
//       }
//     );

//     // Extract the text response
//     const textResponse =
//       response.data?.candidates?.[0]?.content?.parts?.[0]?.text;

//     if (!textResponse) {
//       console.warn("⚠️ Gemini response missing expected text part.", response.data);
//       return res.json({
//         success: true,
//         llm_output: "No text response generated by the model.",
//       });
//     }

//     res.json({
//       success: true,
//       llm_output: textResponse,
//     });

//   } catch (error) {
//     // Log more detailed error information
//     console.error("❌ Gemini Error:", error.message);
//     if (error.response) {
//       console.error("Data:", error.response.data);
//       console.error("Status:", error.response.status);
//       console.error("Headers:", error.response.headers);
//     } else if (error.request) {
//       console.error("Request:", error.request);
//     }

//     res.status(500).json({
//       error: "Failed to process image with Gemini",
//       details: error.response?.data?.error?.message || error.message,
//     });
//   }
// });


// app.post("/ask-question", async (req, res) => {
//   try {
//     if (!GEMINI_API_KEY) {
//       console.error("❌ GEMINI_API_KEY environment variable not set.");
//       return res.status(500).json({
//         error: "Server configuration error: API key not set.",
//       });
//     }

//     const { prompt } = req.body;

//     if (!prompt) {
//       return res.status(400).json({ error: "No prompt provided" });
//     }

    
//     const systemInstruction = {
//       parts: [{
//         text: "You are a fun assistant. Your replies should be short and a little silly, while still being helpful and answering the question."
//       }]
//     };

//     const payload = {
//       contents: [
//         {
//           role: "user",
//           parts: [{ text: prompt }],
//         },
//       ],
    
//       systemInstruction: systemInstruction,
//     };

//     const response = await axios.post(
//       `${GEMINI_API_URL}?key=${GEMINI_API_KEY}`,
//       payload,
//       {
//         headers: {
//           "Content-Type": "application/json",
//         },
//       }
//     );

//     const textResponse =
//       response.data?.candidates?.[0]?.content?.parts?.[0]?.text;

//     if (!textResponse) {
//       console.warn("⚠️ Gemini response missing expected text part.", response.data);
//       return res.json({
//         success: true,
//         llm_output: "The model was too goofy and forgot to reply!",
//       });
//     }

//     res.json({
//       success: true,
//       llm_output: textResponse,
//     });

//   } catch (error) {
    
//     console.error("❌ Gemini Error (/ask-question):", error.message);
//     if (error.response) {
//       console.error("Data:", error.response.data);
//       console.error("Status:", error.response.status);
//     } else if (error.request) {
//       console.error("Request:", error.request);
//     }

//     res.status(500).json({
//       error: "Failed to process text prompt with Gemini",
//       details: error.response?.data?.error?.message || error.message,
//     });
//   }
// });

// const PORT = process.env.PORT || 3000;
// app.listen(PORT, () => {
//   console.log(`🚀 Server running on port ${PORT}`);
//   console.log(`POST to http://localhost:${PORT}/process-image`);
//   console.log(`POST to http://localhost:${PORT}/ask-question`); 
//   if (!GEMINI_API_KEY) {
//     console.warn("⚠️ WARNING: GEMINI_API_KEY environment variable is not set!");
//     console.warn("The /process-image endpoint will not work until it is set.");
//   }
// });

const express = require('express');
const fs = require('fs');
const path = require('path');
const cors = require('cors'); // Import the CORS middleware
const app = express();

// The port the real ESP32-CAM capture server runs on
const MOCK_PORT = 81;

// The placeholder image to send
const IMAGE_FILE = path.join(__dirname, 'test_image.jpg');

// --- NEW ---
// Use CORS to allow other websites (like our test HTML file)
// to make requests to this server.
app.use(cors());
// -----------

/**
 * @route GET /capture
 * @description Simulates the ESP32-CAM's capture endpoint.
 */
app.get('/capture', (req, res) => {
  console.log(`[Mock ESP32]: Received /capture request. Sending test image...`);

  // Check if the test image exists
  if (!fs.existsSync(IMAGE_FILE)) {
    console.error(`Error: test_image.jpg not found!`);
    console.error(`Please add a file named 'test_image.jpg' in this directory: ${__dirname}`);
    return res.status(500).send('Mock server is missing test_image.jpg');
  }

  try {
    // Read the image file as a raw buffer
    const imageBuffer = fs.readFileSync(IMAGE_FILE);

    // Send the image back, just like the ESP32-CAM would
    res.setHeader('Content-Type', 'image/jpeg');
    res.send(imageBuffer);

  } catch (error) {
    console.error('Error reading image file:', error);
    res.status(500).send('Error reading mock image file');
  }
});

app.listen(MOCK_PORT, () => {
  console.log(`----------------------------------------------------`);
  console.log(`🚀 Mock ESP32-CAM server running!`);
  console.log(`   (Now with CORS enabled for frontend testing)`);
  console.log(`Listening on: http://127.0.0.1:${MOCK_PORT}`);
  console.log(`Endpoint ready: http://127.0.0.1:${MOCK_PORT}/capture`);
  console.log(`----------------------------------------------------`);
});